# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JObyKvGd_gGk0BJ1NtqneFpsFbsy6XBw
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Veridi Logistics Auditor",
    page_icon="🚚",
    layout="wide"
)

PALETTE = {
    'on_time':    '#2ecc71',
    'late':       '#e67e22',
    'super_late': '#e74c3c',
    'primary':    '#2c3e50',
    'accent':     '#3498db',
}

# ── Load data ──────────────────────────────────────────────────────────────────
@st.cache_data
def load_data():
    df = pd.read_csv('veridi_master_dashboard_data.csv')
    df['order_purchase_timestamp']      = pd.to_datetime(df['order_purchase_timestamp'], errors='coerce')
    df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'], errors='coerce')
    df['order_estimated_delivery_date'] = pd.to_datetime(df['order_estimated_delivery_date'], errors='coerce')
    return df

df = load_data()

# ── Sidebar filters ────────────────────────────────────────────────────────────
st.sidebar.image("https://img.icons8.com/emoji/96/delivery-truck.png", width=80)
st.sidebar.title("🔍 Filters")

all_states = sorted(df['customer_state'].dropna().unique())
selected_states = st.sidebar.multiselect(
    "Customer State", all_states, default=all_states
)

all_statuses = ['On Time', 'Late', 'Super Late']
selected_statuses = st.sidebar.multiselect(
    "Delivery Status", all_statuses, default=all_statuses
)

all_months = sorted(df['order_year_month'].dropna().unique())
month_range = st.sidebar.select_slider(
    "Month Range",
    options=all_months,
    value=(all_months[0], all_months[-1])
)

# ── Apply filters ──────────────────────────────────────────────────────────────
filtered = df[
    df['customer_state'].isin(selected_states) &
    df['delivery_status'].isin(selected_statuses) &
    df['order_year_month'].between(month_range[0], month_range[1])
]

# ── Title ──────────────────────────────────────────────────────────────────────
st.title("🚚 Veridi Logistics — Last Mile Delivery Audit")
st.caption("Olist Brazilian E-Commerce Dataset | AmaliTech Capstone")
st.divider()

# ══════════════════════════════════════════════════════════════════════════════
# KPI CARDS
# ══════════════════════════════════════════════════════════════════════════════
total      = len(filtered)
late_pct   = (filtered['is_late'].sum() / total * 100) if total else 0
avg_review = filtered['review_score'].mean()
avg_delay  = filtered['Days_Difference'].mean()

k1, k2, k3, k4 = st.columns(4)
k1.metric("📦 Total Orders",       f"{total:,}")
k2.metric("⏰ Late Delivery Rate",  f"{late_pct:.1f}%",
          delta=f"{late_pct - 20:.1f}% vs 20% target", delta_color="inverse")
k3.metric("⭐ Avg Review Score",    f"{avg_review:.2f} / 5"  if not pd.isna(avg_review) else "N/A")
k4.metric("📅 Avg Days Difference", f"{avg_delay:.1f} days"  if not pd.isna(avg_delay) else "N/A")

st.divider()

# ══════════════════════════════════════════════════════════════════════════════
# ROW 1 — Delivery status breakdown + State bar chart
# ══════════════════════════════════════════════════════════════════════════════
col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("📊 Delivery Status Breakdown")
    status_counts = filtered['delivery_status'].value_counts()
    if not status_counts.empty:
        fig, ax = plt.subplots(figsize=(5, 5))
        colors = [PALETTE['on_time'], PALETTE['late'], PALETTE['super_late']]
        # Only use colors for statuses that exist
        existing = status_counts.index.tolist()
        color_map = {'On Time': PALETTE['on_time'],
                     'Late': PALETTE['late'],
                     'Super Late': PALETTE['super_late']}
        pie_colors = [color_map[s] for s in existing]
        ax.pie(status_counts, labels=status_counts.index, autopct='%1.1f%%',
               colors=pie_colors, startangle=140, textprops={'fontsize': 11})
        ax.set_facecolor('none')
        fig.patch.set_alpha(0)
        st.pyplot(fig)
        plt.close()
    else:
        st.info("No data for selected filters.")

with col2:
    st.subheader("🗺️ Late Delivery Rate by State")
    state_stats = (
        filtered
        .groupby('customer_state')
        .agg(total=('order_id', 'count'), late=('is_late', 'sum'))
        .assign(late_pct=lambda d: d['late'] / d['total'] * 100)
        .sort_values('late_pct', ascending=False)
        .reset_index()
    )
    if not state_stats.empty:
        fig, ax = plt.subplots(figsize=(10, max(4, len(state_stats) * 0.35)))

        def bar_color(pct):
            if pct >= 25: return PALETTE['super_late']
            if pct >= 15: return PALETTE['late']
            return PALETTE['on_time']

        bar_colors = [bar_color(p) for p in state_stats['late_pct']]
        bars = ax.barh(state_stats['customer_state'], state_stats['late_pct'],
                       color=bar_colors, edgecolor='white', linewidth=0.5)
        for bar, val in zip(bars, state_stats['late_pct']):
            ax.text(bar.get_width() + 0.3,
                    bar.get_y() + bar.get_height() / 2,
                    f'{val:.1f}%', va='center', fontsize=8)
        nat_avg = state_stats['late_pct'].mean()
        ax.axvline(nat_avg, color=PALETTE['primary'], linestyle='--',
                   linewidth=1.5, label=f'Avg: {nat_avg:.1f}%')
        ax.set_xlabel('% Late Deliveries')
        ax.xaxis.set_major_formatter(mtick.PercentFormatter())
        ax.invert_yaxis()
        ax.legend(fontsize=9)
        ax.set_facecolor('none')
        fig.patch.set_alpha(0)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

st.divider()

# ══════════════════════════════════════════════════════════════════════════════
# ROW 2 — Sentiment correlation + Avg review by status
# ══════════════════════════════════════════════════════════════════════════════
col3, col4 = st.columns(2)

with col3:
    st.subheader("⭐ Avg Review Score by Delivery Status")
    has_review = filtered[filtered['review_score'].notna()]
    avg_by_status = (
        has_review.groupby('delivery_status')['review_score']
        .mean()
        .reindex(['On Time', 'Late', 'Super Late'])
        .dropna()
    )
    if not avg_by_status.empty:
        fig, ax = plt.subplots(figsize=(6, 4))
        color_map = {'On Time': PALETTE['on_time'],
                     'Late': PALETTE['late'],
                     'Super Late': PALETTE['super_late']}
        bar_cols = [color_map[s] for s in avg_by_status.index]
        bars = ax.bar(avg_by_status.index, avg_by_status.values,
                      color=bar_cols, edgecolor='white', width=0.5)
        for bar, val in zip(bars, avg_by_status.values):
            ax.text(bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + 0.05,
                    f'{val:.2f} ⭐', ha='center', fontsize=11, fontweight='bold')
        ax.set_ylim(0, 5.5)
        ax.set_ylabel('Average Review Score')
        ax.set_facecolor('none')
        fig.patch.set_alpha(0)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

with col4:
    st.subheader("📉 Delay Days vs Review Score")
    has_both = filtered[
        filtered['review_score'].notna() &
        filtered['Days_Difference'].notna()
    ].copy()
    if not has_both.empty:
        bins = list(range(-30, 21, 2))
        has_both['delay_bin'] = pd.cut(has_both['Days_Difference'], bins=bins)
        binned = (
            has_both.groupby('delay_bin', observed=True)['review_score']
            .agg(['mean', 'count']).reset_index()
        )
        binned['bin_mid'] = binned['delay_bin'].apply(lambda x: x.mid)
        fig, ax = plt.subplots(figsize=(6, 4))
        sc = ax.scatter(binned['bin_mid'], binned['mean'],
                        s=binned['count'] / 5, alpha=0.75,
                        c=binned['bin_mid'], cmap='RdYlGn', vmin=-20, vmax=10)
        ax.axvline(0, color=PALETTE['super_late'], linestyle='--',
                   linewidth=1.5, label='Promise boundary')
        ax.set_xlabel('Days Ahead (+) / Behind (−) Estimate')
        ax.set_ylabel('Avg Review Score')
        ax.set_ylim(1, 5.2)
        ax.legend(fontsize=9)
        plt.colorbar(sc, ax=ax, label='Days ahead/behind')
        ax.set_facecolor('none')
        fig.patch.set_alpha(0)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

st.divider()

# ══════════════════════════════════════════════════════════════════════════════
# ROW 3 — Monthly trend
# ══════════════════════════════════════════════════════════════════════════════
st.subheader("📅 Monthly Trend — Volume, Late Rate & Review Score")

monthly = (
    filtered
    .groupby('order_year_month')
    .agg(total_orders=('order_id', 'count'),
         late_orders=('is_late', 'sum'),
         avg_review=('review_score', 'mean'))
    .assign(late_pct=lambda d: d['late_orders'] / d['total_orders'] * 100)
    .reset_index()
)

if not monthly.empty:
    fig, ax1 = plt.subplots(figsize=(14, 5))
    x = range(len(monthly))

    ax1.bar(x, monthly['total_orders'], color=PALETTE['accent'],
            alpha=0.35, label='Total Orders', width=0.8)
    ax1.set_ylabel('Total Orders', color=PALETTE['accent'])
    ax1.tick_params(axis='y', labelcolor=PALETTE['accent'])

    ax2 = ax1.twinx()
    ax2.plot(x, monthly['late_pct'], color=PALETTE['super_late'],
             linewidth=2.5, marker='o', markersize=5, label='Late Rate %')
    ax2.set_ylabel('Late Rate (%)', color=PALETTE['super_late'])
    ax2.tick_params(axis='y', labelcolor=PALETTE['super_late'])
    ax2.yaxis.set_major_formatter(mtick.PercentFormatter())

    ax3 = ax1.twinx()
    ax3.spines['right'].set_position(('outward', 55))
    ax3.plot(x, monthly['avg_review'], color=PALETTE['on_time'],
             linewidth=2.5, linestyle='--', marker='s', markersize=5,
             label='Avg Review ⭐')
    ax3.set_ylabel('Avg Review Score', color=PALETTE['on_time'])
    ax3.set_ylim(1, 5.5)
    ax3.tick_params(axis='y', labelcolor=PALETTE['on_time'])

    step = max(1, len(monthly) // 12)
    ax1.set_xticks(list(x)[::step])
    ax1.set_xticklabels(monthly['order_year_month'].iloc[::step],
                        rotation=45, ha='right')

    lines = (ax1.get_legend_handles_labels()[0] +
             ax2.get_legend_handles_labels()[0] +
             ax3.get_legend_handles_labels()[0])
    labels = (ax1.get_legend_handles_labels()[1] +
              ax2.get_legend_handles_labels()[1] +
              ax3.get_legend_handles_labels()[1])
    ax1.legend(lines, labels, loc='upper left', fontsize=9)
    ax1.set_facecolor('none')
    fig.patch.set_alpha(0)
    plt.tight_layout()
    st.pyplot(fig)
    plt.close()

st.divider()

# ══════════════════════════════════════════════════════════════════════════════
# ROW 4 — Category breakdown
# ══════════════════════════════════════════════════════════════════════════════
st.subheader("📦 Late Rate by Product Category (English)")

cat_stats = (
    filtered[filtered['product_category_name_english'].notna()]
    .groupby('product_category_name_english')
    .agg(total=('order_id', 'count'), late=('is_late', 'sum'))
    .query('total >= 50')
    .assign(late_pct=lambda d: d['late'] / d['total'] * 100)
    .sort_values('late_pct', ascending=False)
    .reset_index()
)

if not cat_stats.empty:
    top_n = st.slider("Show top N categories", 5, 30, 15)
    top_cats = cat_stats.head(top_n)

    fig, ax = plt.subplots(figsize=(12, max(4, top_n * 0.4)))
    bars = ax.barh(top_cats['product_category_name_english'],
                   top_cats['late_pct'],
                   color=PALETTE['super_late'], edgecolor='white', linewidth=0.5)
    for bar, val in zip(bars, top_cats['late_pct']):
        ax.text(bar.get_width() + 0.2,
                bar.get_y() + bar.get_height() / 2,
                f'{val:.1f}%', va='center', fontsize=9)
    ax.invert_yaxis()
    ax.set_xlabel('% Late Deliveries')
    ax.xaxis.set_major_formatter(mtick.PercentFormatter())
    ax.set_facecolor('none')
    fig.patch.set_alpha(0)
    plt.tight_layout()
    st.pyplot(fig)
    plt.close()

st.divider()

# ══════════════════════════════════════════════════════════════════════════════
# RAW DATA TABLE
# ══════════════════════════════════════════════════════════════════════════════
with st.expander("🔎 View Raw Data Sample"):
    st.dataframe(
        filtered[[
            'order_id', 'customer_state', 'delivery_status',
            'Days_Difference', 'review_score',
            'product_category_name_english', 'order_year_month'
        ]].head(500),
        use_container_width=True
    )

st.caption("Built for AmaliTech Capstone — Veridi Logistics Audit")


# ---

# ## How to deploy it

# **Step 1 — Create a `requirements.txt` file** with this content:
# ```
# streamlit
# pandas
# matplotlib
# seaborn
# ```

# **Step 2 — Your GitHub repo needs these 3 files:**
# ```
# your-repo/
# ├── app.py
# ├── requirements.txt
# └── veridi_master_dashboard_data.csv
